-- =============================================================================
-- Module 6: Medical Coding
-- Migration 16: Seed a representative sample of the ICD-10-CM, CPT/HCPCS,
-- and modifier reference libraries - common outpatient codes across several
-- specialties. This is a working sample, not the full code set (ICD-10-CM
-- alone has ~70,000 codes) - see README "Future Improvements" for the plan
-- to load the full NLM/CMS code sets.
-- =============================================================================

insert into public.icd10_codes (code, description, category) values
  ('E11.9',   'Type 2 diabetes mellitus without complications',            'Endocrine, nutritional and metabolic diseases'),
  ('E11.65',  'Type 2 diabetes mellitus with hyperglycemia',               'Endocrine, nutritional and metabolic diseases'),
  ('E78.5',   'Hyperlipidemia, unspecified',                               'Endocrine, nutritional and metabolic diseases'),
  ('E03.9',   'Hypothyroidism, unspecified',                               'Endocrine, nutritional and metabolic diseases'),
  ('I10',     'Essential (primary) hypertension',                         'Diseases of the circulatory system'),
  ('I25.10',  'Atherosclerotic heart disease without angina pectoris',    'Diseases of the circulatory system'),
  ('I48.91',  'Unspecified atrial fibrillation',                         'Diseases of the circulatory system'),
  ('I50.9',   'Heart failure, unspecified',                              'Diseases of the circulatory system'),
  ('J45.909', 'Unspecified asthma, uncomplicated',                       'Diseases of the respiratory system'),
  ('J06.9',   'Acute upper respiratory infection, unspecified',          'Diseases of the respiratory system'),
  ('J20.9',   'Acute bronchitis, unspecified',                           'Diseases of the respiratory system'),
  ('J44.9',   'Chronic obstructive pulmonary disease, unspecified',      'Diseases of the respiratory system'),
  ('K21.9',   'Gastro-esophageal reflux disease without esophagitis',    'Diseases of the digestive system'),
  ('K59.00',  'Constipation, unspecified',                               'Diseases of the digestive system'),
  ('K29.70',  'Gastritis, unspecified, without bleeding',                'Diseases of the digestive system'),
  ('M54.50',  'Low back pain, unspecified',                              'Diseases of the musculoskeletal system'),
  ('M25.50',  'Pain in unspecified joint',                               'Diseases of the musculoskeletal system'),
  ('M79.10',  'Myalgia, unspecified site',                               'Diseases of the musculoskeletal system'),
  ('M17.9',   'Osteoarthritis of knee, unspecified',                     'Diseases of the musculoskeletal system'),
  ('F32.9',   'Major depressive disorder, single episode, unspecified',  'Mental, behavioral and neurodevelopmental disorders'),
  ('F41.9',   'Anxiety disorder, unspecified',                           'Mental, behavioral and neurodevelopmental disorders'),
  ('F41.1',   'Generalized anxiety disorder',                            'Mental, behavioral and neurodevelopmental disorders'),
  ('G47.00',  'Insomnia, unspecified',                                   'Diseases of the nervous system'),
  ('G43.909', 'Migraine, unspecified, not intractable',                  'Diseases of the nervous system'),
  ('R51.9',   'Headache, unspecified',                                   'Symptoms, signs and abnormal findings'),
  ('R05.9',   'Cough, unspecified',                                      'Symptoms, signs and abnormal findings'),
  ('R10.9',   'Unspecified abdominal pain',                              'Symptoms, signs and abnormal findings'),
  ('R53.83',  'Other fatigue',                                           'Symptoms, signs and abnormal findings'),
  ('R42',     'Dizziness and giddiness',                                 'Symptoms, signs and abnormal findings'),
  ('N39.0',   'Urinary tract infection, site not specified',            'Diseases of the genitourinary system'),
  ('N18.3',   'Chronic kidney disease, stage 3',                         'Diseases of the genitourinary system'),
  ('L30.9',   'Dermatitis, unspecified',                                 'Diseases of the skin'),
  ('L20.9',   'Atopic dermatitis, unspecified',                          'Diseases of the skin'),
  ('H52.4',   'Presbyopia',                                              'Diseases of the eye and adnexa'),
  ('H66.90',  'Otitis media, unspecified, unspecified ear',             'Diseases of the ear and mastoid process'),
  ('Z00.00',  'Encounter for general adult medical examination',        'Factors influencing health status'),
  ('Z23',     'Encounter for immunization',                             'Factors influencing health status'),
  ('Z79.4',   'Long term (current) use of insulin',                     'Factors influencing health status'),
  ('Z71.3',   'Dietary counseling and surveillance',                    'Factors influencing health status'),
  ('O26.90',  'Pregnancy related conditions, unspecified trimester',    'Pregnancy, childbirth and the puerperium'),
  ('S93.401A','Sprain of ankle, unspecified, initial encounter',        'Injury, poisoning and external causes')
on conflict (code) do nothing;

insert into public.procedure_codes (code, code_set, description, category) values
  ('99201', 'CPT', 'Office visit, new patient, straightforward',            'Evaluation and Management'),
  ('99202', 'CPT', 'Office visit, new patient, low complexity',             'Evaluation and Management'),
  ('99203', 'CPT', 'Office visit, new patient, moderate complexity',        'Evaluation and Management'),
  ('99204', 'CPT', 'Office visit, new patient, high complexity',            'Evaluation and Management'),
  ('99211', 'CPT', 'Office visit, established patient, minimal',            'Evaluation and Management'),
  ('99212', 'CPT', 'Office visit, established patient, straightforward',    'Evaluation and Management'),
  ('99213', 'CPT', 'Office visit, established patient, low complexity',     'Evaluation and Management'),
  ('99214', 'CPT', 'Office visit, established patient, moderate complexity','Evaluation and Management'),
  ('99215', 'CPT', 'Office visit, established patient, high complexity',    'Evaluation and Management'),
  ('99381', 'CPT', 'Initial preventive visit, infant',                      'Preventive Medicine'),
  ('99395', 'CPT', 'Periodic preventive visit, 18-39 years',                'Preventive Medicine'),
  ('99396', 'CPT', 'Periodic preventive visit, 40-64 years',                'Preventive Medicine'),
  ('99406', 'CPT', 'Smoking cessation counseling, 3-10 minutes',            'Preventive Medicine'),
  ('90471', 'CPT', 'Immunization administration, one vaccine',              'Medicine'),
  ('90715', 'CPT', 'Tdap vaccine administration',                           'Medicine'),
  ('93000', 'CPT', 'Electrocardiogram, complete',                          'Medicine'),
  ('94010', 'CPT', 'Spirometry',                                          'Medicine'),
  ('36415', 'CPT', 'Collection of venous blood by venipuncture',           'Medicine'),
  ('80053', 'CPT', 'Comprehensive metabolic panel',                       'Pathology and Laboratory'),
  ('80061', 'CPT', 'Lipid panel',                                         'Pathology and Laboratory'),
  ('83036', 'CPT', 'Hemoglobin A1C',                                      'Pathology and Laboratory'),
  ('85025', 'CPT', 'Complete blood count with differential',              'Pathology and Laboratory'),
  ('81003', 'CPT', 'Urinalysis, automated, without microscopy',           'Pathology and Laboratory'),
  ('84443', 'CPT', 'Thyroid stimulating hormone (TSH)',                   'Pathology and Laboratory'),
  ('71046', 'CPT', 'Chest X-ray, 2 views',                                'Radiology'),
  ('73030', 'CPT', 'Shoulder X-ray, 2+ views',                            'Radiology'),
  ('72110', 'CPT', 'Lumbar spine X-ray, 4+ views',                        'Radiology'),
  ('76700', 'CPT', 'Abdominal ultrasound, complete',                      'Radiology'),
  ('20610', 'CPT', 'Arthrocentesis, major joint',                         'Surgery'),
  ('12001', 'CPT', 'Simple repair, superficial wound, 2.5 cm or less',    'Surgery'),
  ('17110', 'CPT', 'Destruction of benign lesions, up to 14',             'Surgery'),
  ('99070', 'HCPCS','Supplies and materials provided by physician',       'Supplies'),
  ('A0425', 'HCPCS','Ground mileage, per statute mile',                   'Ambulance'),
  ('A0428', 'HCPCS','Ambulance service, basic life support, non-emergency','Ambulance'),
  ('E0114', 'HCPCS','Crutches, underarm, pair',                          'DME'),
  ('E0130', 'HCPCS','Walker, rigid, wheeled',                            'DME'),
  ('J1885', 'HCPCS','Injection, ketorolac tromethamine, per 15 mg',      'Drugs'),
  ('J3420', 'HCPCS','Injection, vitamin B-12, per 1000 mcg',             'Drugs'),
  ('G0008', 'HCPCS','Administration of influenza virus vaccine',        'Preventive'),
  ('G0009', 'HCPCS','Administration of pneumococcal vaccine',           'Preventive'),
  ('G0439', 'HCPCS','Annual wellness visit, subsequent',                'Preventive')
on conflict (code) do nothing;

insert into public.modifiers (code, description) values
  ('25', 'Significant, separately identifiable E/M service by the same physician on the same day'),
  ('26', 'Professional component'),
  ('50', 'Bilateral procedure'),
  ('51', 'Multiple procedures'),
  ('52', 'Reduced services'),
  ('53', 'Discontinued procedure'),
  ('57', 'Decision for surgery'),
  ('59', 'Distinct procedural service'),
  ('76', 'Repeat procedure by same physician'),
  ('77', 'Repeat procedure by another physician'),
  ('78', 'Unplanned return to the operating/procedure room'),
  ('79', 'Unrelated procedure or service during the postoperative period'),
  ('80', 'Assistant surgeon'),
  ('91', 'Repeat clinical diagnostic laboratory test'),
  ('95', 'Synchronous telemedicine service'),
  ('GT', 'Via interactive audio and video telecommunication systems'),
  ('LT', 'Left side'),
  ('RT', 'Right side'),
  ('TC', 'Technical component')
on conflict (code) do nothing;
